import { DayOfWeek, FulfilmentMethod, VerificationStatus } from "@/domain/enums";
import type { Business } from "@/domain/types";

export const mockBusinesses: Business[] = [
  // ---- Bakery / Cakes ----
  {
    id: "biz-01",
    slug: "divini-cakes-colombo",
    name: "Divini Cakes",
    description:
      "Colombo's most-loved custom cake studio. We craft artistic fondant cakes, drip cakes, and signature dessert boxes for every occasion — from intimate birthdays to grand weddings.",
    logo: "https://images.unsplash.com/photo-1519915028121-7d3463d5b1ef?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=1200&h=400&fit=crop",
    categoryIds: ["cat-02"],
    location: {
      address: "42 Havelock Road",
      city: "Colombo 5",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 234 5678",
      whatsapp: "+94 77 234 5678",
      email: "hello@divinicakes.lk",
      instagram: "@divinicakes.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.9,
    reviewCount: 312,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: true,
    createdAt: "2023-01-15T08:00:00Z",
  },
  {
    id: "biz-02",
    slug: "sweetbite-bakery-kandy",
    name: "Sweetbite Bakery",
    description:
      "Family-run bakery in the heart of Kandy offering freshly baked breads, pastries, and custom celebration cakes made with local ingredients.",
    logo: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&h=400&fit=crop",
    categoryIds: ["cat-02"],
    location: {
      address: "18 Dalada Veediya",
      city: "Kandy",
      district: "Kandy",
    },
    contactInformation: {
      phone: "+94 81 223 4567",
      whatsapp: "+94 77 456 7890",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "07:00", closeTime: "19:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "08:00", closeTime: "14:00" },
    ],
    rating: 4.6,
    reviewCount: 187,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2022-06-01T08:00:00Z",
  },
  // ---- Photography ----
  {
    id: "biz-03",
    slug: "lens-by-lahiru",
    name: "Lens by Lahiru",
    description:
      "Award-winning wedding and portrait photographer based in Colombo. Capturing emotions, not just moments — with a cinematic, editorial style.",
    logo: "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=400&fit=crop",
    categoryIds: ["cat-12"],
    location: {
      address: "Studio 7, Thimbirigasyaya Road",
      city: "Colombo 5",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 890 1234",
      whatsapp: "+94 77 890 1234",
      email: "lahiru@lensbylahiru.lk",
      instagram: "@lensbylahiru",
      website: "https://lensbylahiru.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "10:00", closeTime: "16:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 5.0,
    reviewCount: 94,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: true,
    createdAt: "2021-09-10T08:00:00Z",
  },
  // ---- Henna ----
  {
    id: "biz-04",
    slug: "nuha-henna-art",
    name: "Nuha Henna Art",
    description:
      "Professional henna artist specialising in bridal mehendi, Arabic, and traditional Sri Lankan designs. Available for events, home visits, and studio appointments.",
    logo: "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=1200&h=400&fit=crop",
    categoryIds: ["cat-09"],
    location: {
      address: "24 Maradana Road",
      city: "Colombo 10",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 76 345 6789",
      whatsapp: "+94 76 345 6789",
      instagram: "@nuha.henna",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: false },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "09:00", closeTime: "20:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
    ],
    rating: 4.8,
    reviewCount: 143,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: true,
    createdAt: "2022-03-20T08:00:00Z",
  },
  // ---- Clothing ----
  {
    id: "biz-05",
    slug: "lace-and-thread-studio",
    name: "Lace & Thread Studio",
    description:
      "Bespoke and ready-to-wear women's clothing. From everyday kurtas to stunning bridal collections. Tailoring and custom orders welcome.",
    logo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1200&h=400&fit=crop",
    categoryIds: ["cat-03"],
    location: {
      address: "56 Bauddhaloka Mawatha",
      city: "Colombo 7",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 567 8901",
      whatsapp: "+94 77 567 8901",
      instagram: "@laceandthread.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "10:00", closeTime: "17:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.7,
    reviewCount: 201,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2021-11-01T08:00:00Z",
  },
  // ---- Food & Beverage ----
  {
    id: "biz-06",
    slug: "ammas-kitchen-gampaha",
    name: "Amma's Kitchen",
    description:
      "Authentic Sri Lankan home-cooked meals delivered to your door. Rotating daily menu including rice and curry, kottu, hoppers, and special pittu sets.",
    logo: "https://images.unsplash.com/photo-1606787365010-14b7f73cbba0?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=1200&h=400&fit=crop",
    categoryIds: ["cat-06", "cat-14"],
    location: {
      address: "33 Kandy Road",
      city: "Gampaha",
      district: "Gampaha",
    },
    contactInformation: {
      phone: "+94 33 222 3456",
      whatsapp: "+94 77 678 9012",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "07:00", closeTime: "20:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
    ],
    rating: 4.8,
    reviewCount: 456,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: true,
    createdAt: "2020-05-10T08:00:00Z",
  },
  // ---- Fitness ----
  {
    id: "biz-07",
    slug: "fitlife-personal-training",
    name: "FitLife Personal Training",
    description:
      "One-on-one and group personal training sessions tailored to your goals. Weight loss, muscle gain, functional fitness, and post-natal programmes available.",
    logo: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=400&fit=crop",
    categoryIds: ["cat-08"],
    location: {
      address: "12 Galle Road",
      city: "Nugegoda",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 789 0123",
      whatsapp: "+94 77 789 0123",
      instagram: "@fitlife.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "05:30", closeTime: "21:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "05:30", closeTime: "21:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "05:30", closeTime: "21:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "05:30", closeTime: "21:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "05:30", closeTime: "21:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "06:00", closeTime: "18:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "06:00", closeTime: "12:00" },
    ],
    rating: 4.9,
    reviewCount: 128,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: false,
    createdAt: "2022-01-05T08:00:00Z",
  },
  // ---- Cosmetics ----
  {
    id: "biz-08",
    slug: "glow-cosmetics-colombo",
    name: "Glow Cosmetics",
    description:
      "Sri Lanka's go-to destination for cruelty-free, locally sourced cosmetics and skincare. Featuring our award-winning brightening serum range.",
    logo: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=1200&h=400&fit=crop",
    categoryIds: ["cat-04"],
    location: {
      address: "101 Union Place",
      city: "Colombo 2",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 901 2345",
      whatsapp: "+94 77 901 2345",
      email: "orders@glowcosmetics.lk",
      instagram: "@glowcosmetics.lk",
      website: "https://glowcosmetics.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "10:00", closeTime: "16:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.7,
    reviewCount: 289,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PLATFORM_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: true,
    createdAt: "2021-04-12T08:00:00Z",
  },
  // ---- Gifts & Crafts ----
  {
    id: "biz-09",
    slug: "crafted-with-love-moratuwa",
    name: "Crafted with Love",
    description:
      "Handmade gift boxes, personalised keepsakes, and corporate gifting solutions. Every piece is made to order with care and attention to detail.",
    logo: "https://images.unsplash.com/photo-1513201099705-a9746072788e?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1607344645866-009c320c5ab9?w=1200&h=400&fit=crop",
    categoryIds: ["cat-05"],
    location: {
      address: "77 Rawathawatta Road",
      city: "Moratuwa",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 012 3456",
      whatsapp: "+94 77 012 3456",
      instagram: "@craftedwithlove.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "09:00", closeTime: "15:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.9,
    reviewCount: 172,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2022-07-18T08:00:00Z",
  },
  // ---- Herbal ----
  {
    id: "biz-10",
    slug: "lanka-herbal-wellness",
    name: "Lanka Herbal Wellness",
    description:
      "Traditional Ayurvedic and herbal products sourced from rural Sri Lanka. Oils, tonics, teas and wellness kits crafted using generations-old recipes.",
    logo: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1526510747491-58f928ec870f?w=1200&h=400&fit=crop",
    categoryIds: ["cat-10"],
    location: {
      address: "12 Peradeniya Road",
      city: "Kandy",
      district: "Kandy",
    },
    contactInformation: {
      phone: "+94 81 234 5678",
      whatsapp: "+94 77 123 4567",
      email: "info@lankaherbal.lk",
      website: "https://lankaherbal.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "08:00", closeTime: "14:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.6,
    reviewCount: 98,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.PLATFORM_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2020-11-25T08:00:00Z",
  },
  // ---- Home Decor ----
  {
    id: "biz-11",
    slug: "casa-interiors-colombo",
    name: "Casa Interiors",
    description:
      "Contemporary home decor and furnishings curated for modern Sri Lankan living. From statement pieces to everyday accents, we have everything to transform your space.",
    logo: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=1200&h=400&fit=crop",
    categoryIds: ["cat-11"],
    location: {
      address: "22 Duplication Road",
      city: "Colombo 3",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 234 5679",
      whatsapp: "+94 77 234 5679",
      instagram: "@casainteriors.lk",
      website: "https://casainteriors.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "10:00", closeTime: "19:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "10:00", closeTime: "18:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "11:00", closeTime: "17:00" },
    ],
    rating: 4.5,
    reviewCount: 134,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2021-08-09T08:00:00Z",
  },
  // ---- Education ----
  {
    id: "biz-12",
    slug: "brightminds-academy-nugegoda",
    name: "BrightMinds Academy",
    description:
      "O/L and A/L tuition classes for Mathematics, Science, and English. Small groups ensure personal attention. Online and in-person options available.",
    logo: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1200&h=400&fit=crop",
    categoryIds: ["cat-01"],
    location: {
      address: "45 High Level Road",
      city: "Nugegoda",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 77 345 6780",
      whatsapp: "+94 77 345 6780",
      email: "enrol@brightminds.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "14:00", closeTime: "20:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "14:00", closeTime: "20:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "14:00", closeTime: "20:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "14:00", closeTime: "20:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "14:00", closeTime: "20:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "08:00", closeTime: "14:00" },
    ],
    rating: 4.7,
    reviewCount: 76,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: false,
    createdAt: "2019-02-15T08:00:00Z",
  },
  // ---- Restaurant ----
  {
    id: "biz-13",
    slug: "spice-route-cafe-kollupitiya",
    name: "Spice Route Café",
    description:
      "A vibrant café blending Sri Lankan spices with modern café culture. Signature dishes include our famous kottu waffle and king coconut smoothie bowls.",
    logo: "https://images.unsplash.com/photo-1525610553991-2bede1a236e2?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&h=400&fit=crop",
    categoryIds: ["cat-14", "cat-06"],
    location: {
      address: "9 Kollupitiya Road",
      city: "Colombo 3",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 11 234 5678",
      whatsapp: "+94 77 456 7891",
      instagram: "@spiceroutecafe",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "07:30", closeTime: "22:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "07:30", closeTime: "22:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "07:30", closeTime: "22:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "07:30", closeTime: "22:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "07:30", closeTime: "23:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "08:00", closeTime: "23:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "08:00", closeTime: "21:00" },
    ],
    rating: 4.4,
    reviewCount: 521,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PLATFORM_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: true,
    createdAt: "2018-09-01T08:00:00Z",
  },
  // ---- Professional Services ----
  {
    id: "biz-14",
    slug: "silva-associates-legal",
    name: "Silva & Associates",
    description:
      "Experienced legal consultancy specialising in property law, business registration, and civil matters. Free initial consultation available.",
    logo: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&h=400&fit=crop",
    categoryIds: ["cat-13"],
    location: {
      address: "34 Chatham Street",
      city: "Colombo 1",
      district: "Colombo",
    },
    contactInformation: {
      phone: "+94 11 234 9876",
      email: "consult@silvaassociates.lk",
      website: "https://silvaassociates.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "08:30", closeTime: "17:30" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "08:30", closeTime: "17:30" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "08:30", closeTime: "17:30" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "08:30", closeTime: "17:30" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "08:30", closeTime: "17:00" },
      { day: DayOfWeek.SATURDAY, isOpen: false },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.6,
    reviewCount: 42,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: false,
    createdAt: "2017-01-10T08:00:00Z",
  },
  // ---- Retail & Grocery ----
  {
    id: "biz-15",
    slug: "fresh-harvest-grocery-ja-ela",
    name: "Fresh Harvest Grocery",
    description:
      "Premium quality fresh produce, organic groceries, and pantry essentials delivered island-wide. Sourced directly from local farmers.",
    logo: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200&h=400&fit=crop",
    categoryIds: ["cat-15"],
    location: {
      address: "102 Negombo Road",
      city: "Ja-Ela",
      district: "Gampaha",
    },
    contactInformation: {
      phone: "+94 33 123 4567",
      whatsapp: "+94 77 567 8902",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "06:00", closeTime: "20:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "07:00", closeTime: "18:00" },
    ],
    rating: 4.5,
    reviewCount: 203,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.PLATFORM_DELIVERY, FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2019-07-22T08:00:00Z",
  },
  // ---- Extra Bakery ----
  {
    id: "biz-16",
    slug: "sugarcraft-wattala",
    name: "SugarCraft",
    description:
      "Specialised in wedding cakes, tiered celebration cakes, and cupcake towers. Premium Belgian chocolate used in all our chocolate collections.",
    logo: "https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1562777717-dc6984f65a63?w=1200&h=400&fit=crop",
    categoryIds: ["cat-02"],
    location: {
      address: "14 Negombo Road",
      city: "Wattala",
      district: "Gampaha",
    },
    contactInformation: {
      phone: "+94 77 678 9013",
      whatsapp: "+94 77 678 9013",
      instagram: "@sugarcraft.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "08:00", closeTime: "17:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.8,
    reviewCount: 224,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2020-10-01T08:00:00Z",
  },
  // ---- Extra Food ----
  {
    id: "biz-17",
    slug: "curry-culture-negombo",
    name: "Curry Culture",
    description:
      "Modern Sri Lankan cuisine with a twist. Our curated tasting boxes bring restaurant quality meals to your home. Weekly menus change with seasonal produce.",
    logo: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=1200&h=400&fit=crop",
    categoryIds: ["cat-06"],
    location: {
      address: "77 Main Street",
      city: "Negombo",
      district: "Gampaha",
    },
    contactInformation: {
      phone: "+94 31 222 3456",
      whatsapp: "+94 77 789 0124",
      instagram: "@curryculture.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: false },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "11:00", closeTime: "21:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "11:00", closeTime: "21:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "11:00", closeTime: "21:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "11:00", closeTime: "22:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "10:00", closeTime: "22:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "10:00", closeTime: "20:00" },
    ],
    rating: 4.7,
    reviewCount: 318,
    verificationStatus: VerificationStatus.PENDING,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2021-03-14T08:00:00Z",
  },
  // ---- Extra Cosmetics ----
  {
    id: "biz-18",
    slug: "pure-beauty-matara",
    name: "Pure Beauty",
    description:
      "Natural and organic beauty products handcrafted in Matara. Specialising in coconut-based skincare, herbal hair oils, and chemical-free cosmetics.",
    logo: "https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1200&h=400&fit=crop",
    categoryIds: ["cat-04", "cat-10"],
    location: {
      address: "45 Uyanwatta Road",
      city: "Matara",
      district: "Matara",
    },
    contactInformation: {
      phone: "+94 41 222 3456",
      whatsapp: "+94 77 890 1235",
      instagram: "@purebeauty.lk",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "09:00", closeTime: "14:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.8,
    reviewCount: 167,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.PLATFORM_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2022-02-28T08:00:00Z",
  },
  // ---- Extra Photography ----
  {
    id: "biz-19",
    slug: "visions-by-thilini",
    name: "Visions by Thilini",
    description:
      "Lifestyle and maternity photographer bringing warmth and storytelling to every session. Based in Kandy, available island-wide for weddings and events.",
    logo: "https://images.unsplash.com/photo-1554080353-a576cf803bda?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=1200&h=400&fit=crop",
    categoryIds: ["cat-12"],
    location: {
      address: "8 Peradeniya Road",
      city: "Kandy",
      district: "Kandy",
    },
    contactInformation: {
      phone: "+94 77 901 2346",
      whatsapp: "+94 77 901 2346",
      instagram: "@visionsbythilini",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
      { day: DayOfWeek.SUNDAY, isOpen: true, openTime: "08:00", closeTime: "18:00" },
    ],
    rating: 4.9,
    reviewCount: 88,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [],
    pickupAvailable: false,
    featured: false,
    createdAt: "2023-04-01T08:00:00Z",
  },
  // ---- Extra Clothing ----
  {
    id: "biz-20",
    slug: "threadworks-jaffna",
    name: "Threadworks",
    description:
      "Northern Sri Lanka's premier fashion house specialising in traditional and contemporary Tamil attire, including sarees, Punjabi sets, and formal wear.",
    logo: "https://images.unsplash.com/photo-1467043237213-65f2da53396f?w=200&h=200&fit=crop",
    coverImage:
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=400&fit=crop",
    categoryIds: ["cat-03"],
    location: {
      address: "22 Hospital Road",
      city: "Jaffna",
      district: "Jaffna",
    },
    contactInformation: {
      phone: "+94 21 222 3456",
      whatsapp: "+94 77 012 3457",
      instagram: "@threadworks.jaffna",
    },
    openingHours: [
      { day: DayOfWeek.MONDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.TUESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.WEDNESDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.THURSDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.FRIDAY, isOpen: true, openTime: "09:00", closeTime: "18:00" },
      { day: DayOfWeek.SATURDAY, isOpen: true, openTime: "09:00", closeTime: "17:00" },
      { day: DayOfWeek.SUNDAY, isOpen: false },
    ],
    rating: 4.6,
    reviewCount: 113,
    verificationStatus: VerificationStatus.VERIFIED,
    deliveryOptions: [FulfilmentMethod.BUSINESS_DELIVERY, FulfilmentMethod.PICKUP],
    pickupAvailable: true,
    featured: false,
    createdAt: "2020-08-15T08:00:00Z",
  },
];
