import type { Category } from "@/domain/types";

export const mockCategories: Category[] = [
  {
    id: "cat-01",
    slug: "academy-education",
    name: "Academy & Education",
    description: "Tuition centres, online courses, workshops and educational services",
    icon: "🎓",
    businessCount: 12,
  },
  {
    id: "cat-02",
    slug: "bakery-cakes-desserts",
    name: "Bakery, Cakes & Desserts",
    description: "Custom cakes, pastries, bread and sweet treats",
    icon: "🎂",
    businessCount: 28,
  },
  {
    id: "cat-03",
    slug: "clothing-accessories",
    name: "Clothing & Accessories",
    description: "Fashion, boutique clothing, jewellery and accessories",
    icon: "👗",
    businessCount: 19,
  },
  {
    id: "cat-04",
    slug: "cosmetics-beauty",
    name: "Cosmetics & Beauty",
    description: "Makeup, skincare, beauty products and personal care",
    icon: "💄",
    businessCount: 15,
  },
  {
    id: "cat-05",
    slug: "crafts-gifts-decor",
    name: "Crafts, Gifts & Decor",
    description: "Handmade gifts, crafts, party supplies and decorations",
    icon: "🎁",
    businessCount: 22,
  },
  {
    id: "cat-06",
    slug: "food-beverage",
    name: "Food & Beverage",
    description: "Home-cooked meals, beverages, snacks and specialty foods",
    icon: "🍱",
    businessCount: 35,
  },
  {
    id: "cat-07",
    slug: "general-contact",
    name: "General Contact",
    description: "Businesses that prefer direct communication for enquiries",
    icon: "📞",
    businessCount: 8,
  },
  {
    id: "cat-08",
    slug: "health-fitness",
    name: "Health & Fitness",
    description: "Personal training, yoga, nutrition coaching and wellness",
    icon: "💪",
    businessCount: 14,
  },
  {
    id: "cat-09",
    slug: "henna-mehendi-art",
    name: "Henna & Mehendi Art",
    description: "Traditional and contemporary henna and mehendi designs",
    icon: "🌿",
    businessCount: 11,
  },
  {
    id: "cat-10",
    slug: "herbal-wellness",
    name: "Herbal & Wellness",
    description: "Ayurvedic products, herbal remedies and holistic wellness",
    icon: "🌱",
    businessCount: 9,
  },
  {
    id: "cat-11",
    slug: "home-decor-furnishing",
    name: "Home Decor & Furnishing",
    description: "Interior decor, furniture, home accessories and furnishings",
    icon: "🏡",
    businessCount: 17,
  },
  {
    id: "cat-12",
    slug: "photography-media",
    name: "Photography & Media",
    description: "Photography, videography, editing and media production",
    icon: "📸",
    businessCount: 20,
  },
  {
    id: "cat-13",
    slug: "professional-services",
    name: "Professional Services",
    description: "Legal, accounting, consulting and other professional services",
    icon: "💼",
    businessCount: 13,
  },
  {
    id: "cat-14",
    slug: "restaurant-cafe",
    name: "Restaurant & Cafe",
    description: "Dine-in, takeaway, and catering services",
    icon: "☕",
    businessCount: 31,
  },
  {
    id: "cat-15",
    slug: "retail-grocery",
    name: "Retail & Grocery",
    description: "Grocery stores, retail shops and everyday essentials",
    icon: "🛒",
    businessCount: 24,
  },
];
