import { AddressType, UserRole } from "@/domain/enums";
import type { User } from "@/domain/types";

export const mockUsers: User[] = [
  {
    id: "user-01",
    name: "Aisha Rifath",
    email: "customer@example.com",
    phone: "+94 77 111 2233",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-01",
        userId: "user-01",
        label: "Home",
        type: AddressType.HOME,
        line1: "24/3 Wijerama Mawatha",
        city: "Colombo 7",
        district: "Colombo",
        postalCode: "00700",
        isDefault: true,
      },
      {
        id: "addr-02",
        userId: "user-01",
        label: "Office",
        type: AddressType.WORK,
        line1: "World Trade Centre, Level 12",
        line2: "Echelon Square",
        city: "Colombo 1",
        district: "Colombo",
        postalCode: "00100",
        isDefault: false,
      },
    ],
    createdAt: "2023-03-01T08:00:00Z",
  },
  {
    id: "user-02",
    name: "Kasun Perera",
    email: "kasun.perera@gmail.com",
    phone: "+94 71 223 4455",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-03",
        userId: "user-02",
        label: "Home",
        type: AddressType.HOME,
        line1: "15 Galle Road",
        city: "Dehiwala",
        district: "Colombo",
        isDefault: true,
      },
    ],
    createdAt: "2022-11-15T08:00:00Z",
  },
  {
    id: "user-03",
    name: "Thilini Fernando",
    email: "thilini.f@yahoo.com",
    phone: "+94 76 334 5566",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-04",
        userId: "user-03",
        label: "Home",
        type: AddressType.HOME,
        line1: "88 Kandy Road",
        city: "Kelaniya",
        district: "Gampaha",
        isDefault: true,
      },
    ],
    createdAt: "2023-01-20T08:00:00Z",
  },
  {
    id: "user-04",
    name: "Nuwan Jayasinghe",
    email: "nuwan.j@hotmail.com",
    phone: "+94 77 445 6677",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-05",
        userId: "user-04",
        label: "Home",
        type: AddressType.HOME,
        line1: "33 Stanley Thilakaratne Mawatha",
        city: "Nugegoda",
        district: "Colombo",
        isDefault: true,
      },
    ],
    createdAt: "2022-09-10T08:00:00Z",
  },
  {
    id: "user-05",
    name: "Priya Navaratnam",
    email: "priya.nav@gmail.com",
    phone: "+94 75 556 7788",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-06",
        userId: "user-05",
        label: "Home",
        type: AddressType.HOME,
        line1: "14 Hospital Street",
        city: "Jaffna",
        district: "Jaffna",
        isDefault: true,
      },
    ],
    createdAt: "2023-05-01T08:00:00Z",
  },
  {
    id: "user-06",
    name: "Rashid Mohamed",
    email: "rashid.m@outlook.com",
    phone: "+94 77 667 8899",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-07",
        userId: "user-06",
        label: "Home",
        type: AddressType.HOME,
        line1: "56 Maradana Road",
        city: "Colombo 10",
        district: "Colombo",
        isDefault: true,
      },
    ],
    createdAt: "2022-07-25T08:00:00Z",
  },
  {
    id: "user-07",
    name: "Dilini Wickramasinghe",
    email: "dilini.w@gmail.com",
    phone: "+94 76 778 9900",
    avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-08",
        userId: "user-07",
        label: "Home",
        type: AddressType.HOME,
        line1: "22 Peradeniya Road",
        city: "Kandy",
        district: "Kandy",
        isDefault: true,
      },
    ],
    createdAt: "2023-02-14T08:00:00Z",
  },
  {
    id: "user-08",
    name: "Amara Bandara",
    email: "amara.b@gmail.com",
    phone: "+94 71 889 0011",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-09",
        userId: "user-08",
        label: "Home",
        type: AddressType.HOME,
        line1: "77 Galle Road",
        city: "Galle",
        district: "Galle",
        isDefault: true,
      },
    ],
    createdAt: "2022-04-30T08:00:00Z",
  },
  {
    id: "user-09",
    name: "Sanduni Rathnayake",
    email: "sanduni.r@yahoo.com",
    phone: "+94 77 990 1122",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-10",
        userId: "user-09",
        label: "Home",
        type: AddressType.HOME,
        line1: "44 Baseline Road",
        city: "Colombo 9",
        district: "Colombo",
        isDefault: true,
      },
    ],
    createdAt: "2023-04-12T08:00:00Z",
  },
  {
    id: "user-10",
    name: "Harith de Silva",
    email: "harith.ds@gmail.com",
    phone: "+94 75 001 2233",
    role: UserRole.CUSTOMER,
    addresses: [
      {
        id: "addr-11",
        userId: "user-10",
        label: "Home",
        type: AddressType.HOME,
        line1: "9 D.R. Wijewardena Mawatha",
        city: "Colombo 10",
        district: "Colombo",
        isDefault: true,
      },
    ],
    createdAt: "2022-12-01T08:00:00Z",
  },
];
